name: "Github Action: generate readme"
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 6 * * *"
    
jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Get README.md from my blog
        run: |
          wget -O 'README.md' 'https://raw.githubusercontent.com/HackettYu/mkdocs-material/main/docs/index.md'
           echo -e '\n\n> update on:' $(date) '\n' >> README.md
      - name: Commit files
        run: |
          git config --local user.email "hy.lobyy@gmail.com"
          git config --local user.name "Readme(bot)"
          git commit -m "Github action: updated on $(date +%Y-%m-%d)" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}